Implement task creation functionality
YuraRiabov/SlothOrganizer pull request #9
Opened 2023-01-05 17:07 UTC by YuraRiabov

2023-01-17 17:07 UTC, DZemlyak requested changes

2023-01-19 10:38 UTC, byme8 commented on backend/SlothOrganizer/SlothOrganizer.Domain/Repositories/ITaskRepository.cs
> +        Task<Entities.Task> Insert(Entities.Task task);
We can call Entities.Task as Entities.TaskEntity or Entities.TaskData. Then we don't need any aliases and it would be much cleaner

2023-01-20 11:09 UTC, YuraRiabov commented on backend/SlothOrganizer/SlothOrganizer.Domain/Repositories/IRefreshTokenRepository.cs
> +using Task = System.Threading.Tasks.Task;
Fixed by renaming to UserTask

2023-01-20 11:09 UTC, YuraRiabov commented on backend/SlothOrganizer/SlothOrganizer.Domain/Repositories/ITaskRepository.cs
> +        Task<Entities.Task> Insert(Entities.Task task);
Fixed

2023-01-20 11:09 UTC, YuraRiabov commented on backend/SlothOrganizer/SlothOrganizer.Domain/Repositories/IUserRepository.cs
> +using Task = System.Threading.Tasks.Task;
Fixed

2023-01-20 11:10 UTC, YuraRiabov commented on backend/SlothOrganizer/SlothOrganizer.Services.Abstractions/Utility/IDateTimeService.cs
> +        TimeSpan GetLength(TaskRepeatingPeriod period);
Transferred to separate TaskCompletionPeriodConverter

2023-01-20 11:10 UTC, YuraRiabov commented on frontend/src/app/features/dashboard/dashboard-sidebar/dashboard-sidebar.component.html
> +    <so-task-form (cancel)="clickedOff.emit()" *ngIf="type === 'Create'"></so-task-form>
Fixed

2023-01-20 11:11 UTC, YuraRiabov commented on frontend/src/app/features/dashboard/dashboard-sidebar/dashboard-sidebar.component.ts
> +    @HostListener('document:click', ['$event'])
Usage of angular mat-sidenav solved the problem

2023-01-24 13:53 UTC, DZemlyak approved these changes

2023-01-24 13:54 UTC, merged